# KiBot config file for Zigbee AirQuality Monitor project
kibot:
  version: 1

globals:
  # Filters for KiBot warnings
  filters:
    - filter: Ignore PcbDraw missing components
      number: 103
    - filter: Ignore missing KiCad config, not in docker images
      number: 8
    - filter: Ignore missing KiCad 3D models, not in docker images
      number: 10
    - filter: Ignore missing KiCad config from KiAuto, not in docker images
      number: 58
      regex: kicad_common.json
  # This will undo the `set_text_variables` when we run it locally
  restore_project: true
  # We will use a value externally formatted
  time_reformat: false
  # We want the revision added to the names for this project
  output: '%f-%i_%r.%x'

import:
  - PCBWay.kibot.yaml

preflight:
  check_zone_fills: true
  run_erc: false
  run_drc: false
  # Filters for ERC/DRC errors/warnings
  filters:
    - filter: 'We know some connectors extend outside the board'
      error: 'silk_over_copper'
      regex: 'clipped by solder mask'
  set_text_variables:
    # The revision will be the short git hash
    # We use ${git_hash} for the REV field in the worksheet (frame)
    - name: 'git_hash'
      command: 'git log -1 --format="%h" $KIBOT_PCB_NAME'
      before: 'Git:'
    # Coherent date and time for the schematic and PCB
    # This will be the time stamp of the files generation, not the commit times
    # We use `${date}` for the time field in the worksheet (frame)
    - name: 'date'
      command: 'date --iso-8601=minutes'

outputs:
  - name: 'diff_pcb'
    comment: "Diff of PCB changes against current HEAD"
    type: diff
    dir: Diff
    options:
      pcb: true

  - name: 'diff_sch'
    comment: "Diff of schematic changes against current HEAD"
    type: diff
    dir: Diff
    options:
      pcb: false

  - name: 'bom_xlsx'
    comment: "Spreadsheet for the Bill of Materials"
    type: bom
    dir: BoM
    options: &bom_options
      xlsx:
        datasheet_as_link: MFP
        title: 'Zigbee AirQuality BoM'
        max_col_width: 40
        highlight_empty: false
      columns:
        - Row
        - References
        - Quantity Per PCB
        - field: Value
          join: ['voltage', 'current', 'power', 'tolerance']
        - field: MFN
          name: Manufacturer
        - field: MFP
          name: Manf. Part
        - Footprint
      normalize_values: true

  - name: 'bom_html'
    comment: "HTML for the Bill of Materials"
    type: bom
    dir: BoM
    options:
      <<: *bom_options
      format: HTML
      html:
        datasheet_as_link: MFP
        title: 'Zigbee AirQuality BoM'
        highlight_empty: false

  - name: ibom
    comment: "Interactive Bill of Materials (HTML)"
    type: ibom
    dir: BoM
    options:
      layer_view: F
      blacklist: 'DNF*,TP*'

  - name: 'print_sch'
    comment: "Schematic PDF"
    type: pdf_sch_print
    dir: .

  - name: gerbers
    comment: Gerbers
    type: gerber
    dir: Gerbers
    layers:
      - copper
      - Edge.Cuts
      - F.Silkscreen
      - B.Silkscreen
      - F.Mask
      - B.Mask
      - F.Paste
      - F.Fab
      - F.Courtyard

  - name: drill
    comment: Drill files
    type: excellon
    dir: Drill
    options:
      map:
        type: pdf
      pth_and_npth_single_file: false

  - name: position
    comment: Pick & Place
    type: position
    dir: Position
    options:
      separate_files_for_front_and_back: false

  - name: print_pdf
    comment: "PDF for the PCB"
    type: pcb_print
    dir: PCB
    options:
      force_edge_cuts: true
      keep_temporal_files: true
      # This is the worksheet we selected in the project, no need to specify it again
      # sheet_reference_layout: pcb_print.kicad_wks
      scaling: 2.0
      pages:
        - layers: [ F.Paste, F.Fab ]
          sheet: 'Fabrication layers'
        - layers:
            - layer: F.Cu
            - layer: F.Mask
              color: '#14332440'
            - layer: F.Silkscreen
          sheet: 'Top layer'
        - layers: [ In1.Cu ]
          sheet: 'Inner layer 1'
        - layers: [ In2.Cu ]
          sheet: 'Inner layer 2'
        - layers:
            - layer: B.Cu
            - layer: B.Mask
              color: '#14332440'
            - layer: B.Silkscreen
          sheet: 'Bottom layer'
          mirror: true

  - name: board_top
    comment: "Top layer view"
    type: pcbdraw
    dir: PCB
    options:
      format: jpg
      dpi: 300

  - name: board_top_filled
    comment: "Top layer view with components"
    type: pcbdraw
    dir: PCB
    output_id: '-filled'
    options:
      format: jpg
      dpi: 300
      show_components: all

  - name: board_bottom
    comment: "Bottom layer view"
    type: pcbdraw
    dir: PCB
    options:
      format: jpg
      dpi: 300
      bottom: true

  - name: board_bottom_filled
    comment: "Bottom layer view with components"
    type: pcbdraw
    dir: PCB
    output_id: '-filled'
    options:
      format: jpg
      dpi: 300
      bottom: true
      show_components: all
      
  - name: 3D
    comment: "STEP 3D model"
    type: step
    dir: 3D

  - name: 3D_top_view
    comment: "3D render from top"
    type: render_3d
    dir: 3D
    options:
      zoom: 3
      rotate_x: 3
      rotate_z: 3
      ray_tracing: true

  - name: 3D_top_view_HQ
    comment: "3D render from top (High Quality)"
    type: blender_export
    dir: 3D
    options:
      add_default_light: false
      render_options:
        transparent_background: true
        samples: 20
      outputs:
        - type: blender
        - type: render
      light:
        # [number=0] How powerful is the light. Using 0 for POINT and SUN KiBot will try to use something useful
        - energy: 5
          # [string=''] Name for the light
          name: 'Global Light'
          # [number|string] X position [m]. You can use `width`, `height` and `size` for PCB dimensions
          pos_x: -size*3.33
          # [number|string] Y position [m]. You can use `width`, `height` and `size` for PCB dimensions
          pos_y: size*3.33
          # [number|string] Z position [m]. You can use `width`, `height` and `size` for PCB dimensions
          pos_z: size*8
          # [string='POINT'] [POINT, SUN, SPOT, HEMI, AREA] Type of light. SUN lights will illuminate more evenly
          type: 'SUN'